repos:
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
    -   id: yapf
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
        args: ['--settings-path', '.isort.cfg']
-   repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest -s
        language: system
        pass_filenames: false
        stages: [commit]
