repos:
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
    -   id: yapf
        args: ['-ir', '--style', '.style.yapf']
        additional_dependencies: [toml]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
        args: ['--settings-path', '.isort.cfg']
