# EXPERIMENT
device: 'cuda'
dirpath: 'revamped_scalr_experiments'
exp_name: 'final'
exp_run: 1


# DATA_CONFIG
data:
    sample_chunksize: 10000

    train_val_test:
        full_datapath: '/home/biocusp/data/scp_ad/full.h5ad'

        splitter_config:
            name: GroupSplitter
            params:
                split_ratio: [7, 1, 2.5]
                stratify: 'donor_id'

        # split_datapaths: ''

    # preprocess:
    #     - name: SampleNorm
    #       params:
    #             **args

    #     - name: StandardScaler
    #       params: 
    #             **args

    target: Cell_Type    

feature_selection:

    # scores: '/path/to/matrix'
    feature_chunksize: 6000

    model:
        name: SequentialModel
        params:
            layers: [6000, 6]
            weights_init_zero: True

    model_train_config:
        trainer: SimpleModelTrainer

        dataloader: 
            name: SimpleDataLoader
            params:
                batch_size: 25000
                padding: 6000
        
        optimizer:
            name: SGD
            params:
                lr: 1.0e-3
                weight_decay: 0.1

        loss:
            name: CrossEntropyLoss
        
        epochs: 1

    scoring_config: 
        name: LinearScorer
        
    features_selector:
        name: AbsMean
        params:
            k: 5000


final_training:

    model:
        name: SequentialModel
        params:
            layers: [5000, 6]
            dropout: 0
            weights_init_zero: False

    model_train_config:
        resume_from_checkpoint: null

        trainer: SimpleModelTrainer

        dataloader: 
            name: SimpleDataLoader
            params:
                batch_size: 15000
        
        optimizer:
            name: Adam
            params:
                lr: 1.0e-3
                weight_decay: 0

        loss:
            name: CrossEntropyLoss
        
        epochs: 1

        callbacks:
            - name: TensorboardLogger
            - name: EarlyStopping
              params:
                patience: 3
                min_delta: 1.0e-4
            - name: ModelCheckpoint
              params:
                interval: 5

analysis:

    model_checkpoint: ''

    dataloader:
        name: SimpleDataLoader
        params:
            batch_size: 15000

    gene_analysis:
        scoring_config:
            name: LinearScorer

        features_selector:
            name: ClasswisePromoters
            params:
                k: 100

    # downstream_analysis:
    #     - name: GeneRecallCurve
    #       params:
    #         reference_genes_path: '/home/anand/bioc_repo/single_cell_classification/tutorials/analysis/gene_recall_curve/reference_genes.csv'
    #         top_K: 300
    #         plots_per_row: 3
    #         features_selector:
    #             name: ClasswiseAbs
    #             params: {}
