# EXPERIMENT
device: 'cuda'
dirpath: '.'
exp_name: 'gene_recall_test'
exp_run: 2

# DATA
data:
    sample_chunksize: 10000
    full_datapath: '/home/biocusp/data/scp_ad/full.h5ad'

    split_data:
        split_ratio: [7, 1, 2.5]
        stratify: 'donor_id'

    normalize_samples: True

    # train_datapath: '/path/to/train_data'
    # val_datapath: '/path/to/val_data'
    # test_datapath: '/path/to/test_data'

    target: Cell_Type

# FEATURE SELECTION
feature_selection:

    # weight_matrix: '/path/to/matrix'

    feature_chunksize: 3000
    method_type: feature_chunk

    model:
      name: nn
      params:
          epochs: 1
          batch_size: 15000
          lr: 1.0e-3
          weight_decay: 0.1

    top_features_stats:
        k: 3000
        aggregation_strategy: mean

# MODEL
model:
    type: 'linear'
    hyperparameters:
        layers: [3000, 6]
        dropout: 0
        weights_init_zero: False
    start_checkpoint: null
    resume_from_checkpoint: False

# TRAINING
training:
    opt: 'adam'
    loss: 'log'
    batch_size: 15000
    lr: 1.0e-3
    weight_decay: 0
    epochs: 1
    callbacks:
        tensorboard_logging: True
        early_stop:
            patience: 3
            min_delta: 1.0e-4
        model_checkpoint:
            interval: 5

# ANALYSIS
evaluation:
    model_checkpoint: '/path/to/model'
    batch_size: 15000
    metrics: ['accuracy', 'report']
    # gene_recall:
    #     ## `feature_class_weights_path` & `ranked_genes` are mutually exclusive. Or if you comment out both,
    #     ## then pipeline generated feature_class_weights matrix is used.
    #     # feature_class_weights_path: '/path/to/feature_class_weights matrix csv'
    #     # ranked_genes:
    #     #     per_category: '/path/to/ranked_genes_per_category'
    #     #     aggregated: '/path/to/ranked_genes_aggr_all_categories csv'
    #     reference_genes:
    #         per_category: '/path/to/ref_genes_per_category csv'
    #         aggregated: '/path/to/ref_genes_aggr_all_categories csv'
    #     top_K: 5000
    #     plots_per_row: 5
    deg_config:
        fixed_column: 'Column name in adata.obs which has the condition to subset the anndata, ex: cell_type'
        fixed_condition: 'A condition in fixed_column to subset the anndata, ex : B cell'
        design_factor: 'A column name in adata.obs having factor levels to perform DEG, ex : disease_status'
        factor_categories: 'List of factors in design_factor to perform DEG, ex : [disease, normal] for disease vs normal'
        sum_column: 'A column name in adata.obs to sum the gene expression per unique-id, ex : donor_id'     