# EXPERIMENT
device: 'cuda'
dirpath: '.'
exp_name: 'scalr_test'
exp_run: 0


# DATA_CONFIG
data:
    sample_chunksize: 10000

    train_val_test:
        full_datapath: '/home/biocusp/data/scp_ad/full.h5ad'

        splitter_config:
            name: StratifiedSplitter
            params:
                split_ratio: [7, 1, 2.5]
                stratify: 'donor_id'

        # split_datapaths:

        # final_datapaths:

        # feature_subset_datapaths:

    preprocess:
        - name: SampleNorm
          params:
                **args

        - name: StandardNorm
          params: 
                **args

    target: Cell_Type    

# FEATURE_SELECTION_CONFIG
feature_selection:

    # scores: '/path/to/matrix'
    feature_subset: 3000

    model:
        name: LinearModel
        params:
            layers: [3000, ]

    model_train_config:
        trainer: LinearModelTrainer

        dataloader: 
            name: SimpleDataLoader
            params:
                batch_size: 32
                **args

        loss_fn: CrossEntropyLoss
        opt: Adam
        
        epochs: 1
        batch_size: 15000
        lr: 1.0e-3
        weight_decay: 0.1

    scoring_config: 
        name: LinearScorer
        
    features_selector:
        name: AbsMean
        params:
            k: 5000


# TRAINING
final_training:

    model:
        name: SequentialModel
        params:
            layers: [5000, 6]
            dropout: 0
            weights_init_zero: False

    model_train_config:
        resume_from_checkpoint: null

        trainer: LinearModelTrainer

        dataloader: 
            name: SimpleDataLoader
            params:
                batch_size: 15000
                meta_columns: ['sex', 'disease']
        
        optimizer:
            name: Adam
            params:
                lr: 1.0e-3
                weight_decay: 0

        loss_fn: CrossEntropyLoss
        
        epochs: 1

        callbacks:
            - name: TensorboardLogging
            - name: EarlyStopping
            params:
                patience: 3
                min_delta: 1.0e-4
            - name: ModelCheckpointing
            params:
                interval: 5

# ANALYSIS
downstream_analysis:

    model_checkpoint: '/path/to/model'
    dataloader: SimpleDataLoader
    batch_size: 15000
    
    analysis_methods:

        - name: DEG
          params: **args

        - name: GeneRecall
          params: **args