# EXPERIMENT
device: 'cuda'
dirpath: '.'
exp_name: 'revamped_scalr_test'
exp_run: 0


# DATA_CONFIG
data:
    sample_chunksize: 10000

    train_val_test:
        splitting:
            full_datapath: '/home/biocusp/data/scp_ad/full.h5ad'
            splitter_config:
                name: StratifiedSplitter
                params:
                    split_ratio: [7, 1, 2.5]
                    stratify: 'donor_id'

        # split_datapaths:
        #     train: './revamped_scalr_test_4/data/train_val_test_split/train'
        #     val: './revamped_scalr_test_4/data/train_val_test_split/val'
        #     test: './revamped_scalr_test_4/data/train_val_test_split/test'

        # final_datapaths:
        #     train_datapath: '/path/to/train_data'
        #     val_datapath: '/path/to/val_data'
        #     test_datapath: '/path/to/test_data'

        # feature_subset_datapaths:
        #     train_datapath: '/path/to/train_data'
        #     val_datapath: '/path/to/val_data'
        #     test_datapath: '/path/to/test_data'

    # preprocess:
    #     - name: SampleNorm
    #       params:
    #             **args

    #     - name: StandardNorm
    #       params: 
    #             **args

    target: Cell_Type    

# TRAINING
final_training:

    model:
        name: SequentialModel
        params:
            layers: [22858, 6]
            # dropout: 0
            # weights_init_zero: False

    train_config:
        # resume_from_checkpoint: null

        # trainer: LinearModelTrainer

        dataloader: 
            name: SimpleDataLoader
            params:
                batch_size: 15000
        
        optimizer:
            name: Adam
            params:
                lr: 1.0e-3
                # weight_decay: 0

        # loss:
        #     name: CrossEntropyLoss
        
        # epochs: 1

        callbacks:
            # - name: TensorboardLogging
            - name: EarlyStopping
              params:
                patience: 3
                min_delta: 1.0e-4
            - name: ModelCheckpoint
            # params:
            #     interval: 5