# EXPERIMENT
device: 'cuda'
dirpath: '.'
exp_name: 'scalr_test'
exp_run: 0

# DATA_CONFIG
data:
    sample_chunksize: 10000

    data_splits:
        full_datapath: '/home/biocusp/data/scp_ad/full.h5ad'
        split_data:
            split_ratio: [7, 1, 2.5]
            stratify: 'donor_id'

        # train_datapath: '/path/to/train_data'
        # val_datapath: '/path/to/val_data'
        # test_datapath: '/path/to/test_data'

    preprocess:
        - name: SampleNorm
          params:
                **args

        - name: StandardNorm
          params: 
                **args

    target: Cell_Type    

# FEATURE_SELECTION_CONFIG
feature_selection:

    # scores: '/path/to/matrix'
    scoring_method: 
        name: FeatureChunk
        feature_chunksize: 3000

        model:
            name: LinearModel

        model_train_config:
            trainer: LinearModelTrainer
            dataloader: SimpleDataLoader
            loss_fn: CrossEntropyLoss
            epochs: 1
            batch_size: 15000
            lr: 1.0e-3
            weight_decay: 0.1

    top_features:
        k: 5000
        aggregation_strategy: mix

# TRAINING
final_training:

    model:
        name: LinearModel
        params:
            layers: [3000, 6]
            dropout: 0
            weights_init_zero: False

    model_train_config:
        resume_from_checkpoint: null

        trainer: LinearModelTrainer
        dataloader: SimpleDataLoader
        optimizer: Adam
        loss_fn: CrossEntropyLoss
        batch_size: 15000
        lr: 1.0e-3
        weight_decay: 0
        epochs: 1

        callbacks:
            - name: TensorboardLogging
            - name: EarlyStopping
            params:
                patience: 3
                min_delta: 1.0e-4
            - name: ModelCheckpointing
            params:
                interval: 5

# ANALYSIS
downstream_analysis:

    model_checkpoint: '/path/to/model'
    dataloader: SimpleDataLoader
    batch_size: 15000
    
    analysis_methods:

        - name: DEG
          params: **args

        - name: GeneRecall
          params: **args