# EXPERIMENT
device: 'cuda'
dirpath: '.'
exp_name: 'revamped_scalr_test_fs'
exp_run: 0


# DATA_CONFIG
data:
    sample_chunksize: 10000

    train_val_test:
        # full_datapath: '/home/biocusp/data/scp_ad/full.h5ad'

        # splitter_config:
        #     name: StratifiedSplitter
        #     params:
        #         split_ratio: [7, 1, 2.5]
        #         stratify: 'donor_id'

        split_datapaths: './revamped_scalr_test_5/data/train_val_test_split'

        # final_datapaths:

        # feature_subset_datapaths:

    # preprocess:
    #     - name: SampleNorm
    #       params:
    #             **args

    #     - name: StandardNorm
    #       params: 
    #             **args

    target: Cell_Type    

feature_selection:

    # scores: '/path/to/matrix'
    feature_chunksize: 5000

    model:
        name: SequentialModel
        params:
            layers: [5000, 6]
            weights_init_zero: True

    model_train_config:
        trainer: SimpleModelTrainer

        dataloader: 
            name: SimpleDataLoader
            params:
                batch_size: 25000
        
        optimizer:
            name: SGD
            params:
                lr: 1.0e-3
                weight_decay: 0.1

        # loss:
        #     name: CrossEntropyLoss
        
        epochs: 1

    scoring_config: 
        name: LinearScorer
        
    features_selector:
        name: AbsMean
        params:
            k: 5000


# TRAINING
final_training:

    model:
        name: SequentialModel
        params:
            layers: [5000, 6]
            # dropout: 0
            # weights_init_zero: False

    model_train_config:
        # resume_from_checkpoint: null

        # trainer: LinearModelTrainer

        dataloader: 
            name: SimpleDataLoader
            params:
                batch_size: 15000
        
        optimizer:
            name: Adam
            params:
                lr: 1.0e-3
                # weight_decay: 0

        # loss:
        #     name: CrossEntropyLoss
        
        # epochs: 1

        callbacks:
            # - name: TensorboardLogging
            - name: EarlyStopping
              params:
                patience: 3
                min_delta: 1.0e-4
            - name: ModelCheckpoint
            # params:
            #     interval: 5