data:
  normalize_samples: false
  sample_chunksize: 10000
  target: Cell_Type
  test_datapath: ./scp_e2e_run_1/feature_selection/test
  train_datapath: ./scp_e2e_run_1/feature_selection/train
  val_datapath: ./scp_e2e_run_1/feature_selection/val
device: cuda
dirpath: '/home/anand/bioc_repo/single_cell_classification/examples/gene_recall'
evaluation:
  batch_size: 30000
  gene_recall:
    feature_class_weights_path: '/home/anand/bioc_repo/single_cell_classification/examples/gene_recall/feature_class_weights.csv'
    plots_per_row: 3
    reference_genes:
      per_category: '/home/anand/bioc_repo/single_cell_classification/examples/gene_recall/reference_genes_per_category.csv'
    top_K: 1000
  metrics:
  - accuracy
  - report
  model_checkpoint: ./scp_e2e_run_1/best_model
exp_name: scp_e2e_run
exp_run: 1
feature_selection:
  feature_chunksize: 5000
  method_type: feature_chunk
  model:
    name: nn
    params:
      batch_size: 40000
      epochs: 1
      lr: 0.001
      weight_decay: 0.1
  sample_chunksize: 2000
  store_on_disk: true
  top_features_stats:
    aggregation_strategy: mean
    k: 5000
filepath: .
model:
  hyperparameters:
    dropout: 0
    layers:
    - 5000
    - 6
    weights_init_zero: false
  resume_from_checkpoint: false
  start_checkpoint: null
  type: linear
training:
  batch_size: 40000
  callbacks:
    early_stop:
      min_delta: 0.0001
      patience: 3
    model_checkpoint:
      interval: 5
    tensorboard_logging: true
  epochs: 1
  loss: log
  lr: 0.001
  opt: adam
  weight_decay: 0
