
# EXPERIMENT
full_datapath: '/path/to/anndata.h5ad'
#Path to save the results
dirpath: '/path/to/save/the/result'

dge_type: DgePseudoBulk
# dge_type: DgeLMEM

psedobulk_params: 
        celltype_column: 'cell_type'
        design_factor: 'disease'
        factor_categories: ['COVID-19', 'normal']
        sum_column: 'donor_id'
        cell_subsets: ['non-classical monocyte','natural killer cell']
        min_cell_threshold: 1
        fold_change: 1.5
        p_val: 0.05
        save_plot: True
# lmem_params: 
#         fixed_effect_column: 'disease'
#         fixed_effect_factors: ['COVID-19', 'normal']
#         group: 'donor_id'
#         celltype_column: 'cell_type'
#         cell_subsets: ['non-classical monocyte','natural killer cell']
#         min_cell_threshold: 10
#         n_cpu: 6
#         gene_batch_size: 1000
#         coef_threshold: 0
#         p_val: 0.05
#         save_plot: True
