exp_name: 'scalr_test'
exp_run: 0

data:
    full_datapath: '/path/to/data'
    target: Cell_Type


feature_selection:
    chunksize: 2000
    method_type: feature_chunk
    model:
      params:
          epochs: 25
          batch_size: 15000
    top_features_stats:
        k: 3000


model:
    hyperparameters:
        layers: [3000, 6]


training:
    batch_size: 5000
    epochs: 100


evaluation:
    batch_size: 5000
    metrics: ['accuracy', 'report']
