# Config file for pipeline run.

# DEVICE SETUP.
device: 'cuda'

# EXPERIMENT.
experiment:
    dirpath: 'scalr_experiments'
    exp_name: 'exp_name'
    exp_run: 0


# DATA CONFIG.
data:
    sample_chunksize: 20000
    num_workers: 1

    train_val_test:
        full_datapath: '/path/to/anndata.h5ad'

        splitter_config:
            name: GroupSplitter
            params:
                split_ratio: [7, 1, 2.5]
                stratify: 'donor_id'

        # split_datapaths: ''

    # preprocess:
    #     - name: SampleNorm
    #       params:
    #             **args

    #     - name: StandardScaler
    #       params: 
    #             **args

    target: Cell_Type    


# FEATURE SELECTION.
feature_selection:

    # score_matrix: '/path/to/matrix'
    feature_subsetsize: 5000
    num_workers: 1

    model:
        name: SequentialModel
        params:
            layers: [5000, 6]
            weights_init_zero: True

    model_train_config:
        trainer: SimpleModelTrainer

        dataloader: 
            name: SimpleDataLoader
            params:
                batch_size: 25000
                padding: 5000
        
        optimizer:
            name: SGD
            params:
                lr: 1.0e-3
                weight_decay: 0.1

        loss:
            name: CrossEntropyLoss
        
        epochs: 1

    scoring_config: 
        name: LinearScorer
        
    features_selector:
        name: AbsMean
        params:
            k: 5000


# FINAL MODEL TRAINING.
final_training:

    model:
        name: SequentialModel
        params:
            layers: [5000, 6]
            dropout: 0
            weights_init_zero: False

    model_train_config:
        resume_from_checkpoint: null

        trainer: SimpleModelTrainer

        dataloader: 
            name: SimpleDataLoader
            params:
                batch_size: 15000
        
        optimizer:
            name: Adam
            params:
                lr: 1.0e-3
                weight_decay: 0

        loss:
            name: CrossEntropyLoss
        
        epochs: 1

        callbacks:
            - name: TensorboardLogger
            - name: EarlyStopping
              params:
                patience: 3
                min_delta: 1.0e-4
            - name: ModelCheckpoint
              params:
                interval: 5


# EVALUATION & DOWNSTREAM ANALYSIS.
analysis:

    model_checkpoint: ''

    dataloader:
        name: SimpleDataLoader
        params:
            batch_size: 15000

    gene_analysis:
        scoring_config:
            name: LinearScorer

        features_selector:
            name: ClasswisePromoters
            params:
                k: 100

    # full_samples_downstream_analysis:
    #     - name: DgePseudoBulk
    #       params: **kwargs
    #     - name: DgeLMEM
    #       params: **kwargs      

    # test_samples_downstream_analysis:
    #     - name: GeneRecallCurve
    #       params:
    #         reference_genes_path: '/path/to/reference_genes.csv'
    #         top_K: 300
    #         plots_per_row: 3
    #         features_selector:
    #             name: ClasswiseAbs
    #             params: {}
    #     - name: Heatmap
    #       params: **kwargs
    #     - name: RocAucCurve
    #       params: **kwargs

  