name: YAPF Formatting Check

on: [push]

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run YAPF
      uses: AlexanderMelde/yapf-action@master
      with:
        args: --verbose
